DROP TABLE IF EXISTS films;

CREATE TABLE films (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    film_name TEXT UNIQUE NOT NULL,
    poster TEXT,
    win INTEGER DEFAULT 0,
    lose INTEGER DEFAULT 0,
    rating REAL NOT NULL DEFAULT 0
);
